# coding: utf-8

# flake8: noqa
"""
    Gate API v4

    Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.  # noqa: E501

    Contact: support@mail.gate.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from .account_balance import AccountBalance
from .auto_repay_setting import AutoRepaySetting
from .batch_order import BatchOrder
from .cancel_order import CancelOrder
from .cancel_order_result import CancelOrderResult
from .contract import Contract
from .contract_stat import ContractStat
from .cross_margin_account import CrossMarginAccount
from .cross_margin_account_book import CrossMarginAccountBook
from .cross_margin_balance import CrossMarginBalance
from .cross_margin_borrowable import CrossMarginBorrowable
from .cross_margin_currency import CrossMarginCurrency
from .cross_margin_loan import CrossMarginLoan
from .cross_margin_repay_request import CrossMarginRepayRequest
from .cross_margin_repayment import CrossMarginRepayment
from .cross_margin_transferable import CrossMarginTransferable
from .currency import Currency
from .currency_chain import CurrencyChain
from .currency_pair import CurrencyPair
from .delivery_contract import DeliveryContract
from .delivery_settlement import DeliverySettlement
from .deposit_address import DepositAddress
from .funding_account import FundingAccount
from .funding_book_item import FundingBookItem
from .funding_rate_record import FundingRateRecord
from .futures_account import FuturesAccount
from .futures_account_book import FuturesAccountBook
from .futures_candlestick import FuturesCandlestick
from .futures_initial_order import FuturesInitialOrder
from .futures_liquidate import FuturesLiquidate
from .futures_order import FuturesOrder
from .futures_order_book import FuturesOrderBook
from .futures_order_book_item import FuturesOrderBookItem
from .futures_price_trigger import FuturesPriceTrigger
from .futures_price_triggered_order import FuturesPriceTriggeredOrder
from .futures_ticker import FuturesTicker
from .futures_trade import FuturesTrade
from .insurance_record import InsuranceRecord
from .ledger_record import LedgerRecord
from .loan import Loan
from .loan_patch import LoanPatch
from .loan_record import LoanRecord
from .margin_account import MarginAccount
from .margin_account_book import MarginAccountBook
from .margin_account_currency import MarginAccountCurrency
from .margin_borrowable import MarginBorrowable
from .margin_currency_pair import MarginCurrencyPair
from .margin_transferable import MarginTransferable
from .multi_chain_address_item import MultiChainAddressItem
from .my_futures_trade import MyFuturesTrade
from .open_orders import OpenOrders
from .options_account import OptionsAccount
from .options_account_book import OptionsAccountBook
from .options_contract import OptionsContract
from .options_my_trade import OptionsMyTrade
from .options_order import OptionsOrder
from .options_position import OptionsPosition
from .options_position_close import OptionsPositionClose
from .options_settlement import OptionsSettlement
from .options_ticker import OptionsTicker
from .options_underlying import OptionsUnderlying
from .options_underlying_ticker import OptionsUnderlyingTicker
from .order import Order
from .order_book import OrderBook
from .position import Position
from .position_close import PositionClose
from .position_close_order import PositionCloseOrder
from .repay_request import RepayRequest
from .repayment import Repayment
from .spot_account import SpotAccount
from .spot_price_put_order import SpotPricePutOrder
from .spot_price_trigger import SpotPriceTrigger
from .spot_price_triggered_order import SpotPriceTriggeredOrder
from .sub_account_balance import SubAccountBalance
from .sub_account_transfer import SubAccountTransfer
from .ticker import Ticker
from .total_balance import TotalBalance
from .trade import Trade
from .trade_fee import TradeFee
from .transfer import Transfer
from .trigger_order_response import TriggerOrderResponse
from .withdraw_status import WithdrawStatus
