# coding: utf-8

# flake8: noqa

"""
    Gate API v4

    Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.  # noqa: E501

    Contact: support@mail.gate.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "4.23.2"

# import apis into sdk package
from .api.delivery_api import DeliveryApi
from .api.futures_api import FuturesApi
from .api.margin_api import MarginApi
from .api.options_api import OptionsApi
from .api.spot_api import SpotApi
from .api.wallet_api import WalletApi
from .api.withdrawal_api import WithdrawalApi

# import ApiClient
from .api_client import ApiClient
from .configuration import Configuration
from .exceptions import OpenApiException
from .exceptions import ApiTypeError
from .exceptions import ApiValueError
from .exceptions import ApiKeyError
from .exceptions import ApiException

# import models into sdk package
from .models.account_balance import AccountBalance
from .models.auto_repay_setting import AutoRepaySetting
from .models.batch_order import BatchOrder
from .models.cancel_order import CancelOrder
from .models.cancel_order_result import CancelOrderResult
from .models.contract import Contract
from .models.contract_stat import ContractStat
from .models.cross_margin_account import CrossMarginAccount
from .models.cross_margin_account_book import CrossMarginAccountBook
from .models.cross_margin_balance import CrossMarginBalance
from .models.cross_margin_borrowable import CrossMarginBorrowable
from .models.cross_margin_currency import CrossMarginCurrency
from .models.cross_margin_loan import CrossMarginLoan
from .models.cross_margin_repay_request import CrossMarginRepayRequest
from .models.cross_margin_repayment import CrossMarginRepayment
from .models.cross_margin_transferable import CrossMarginTransferable
from .models.currency import Currency
from .models.currency_chain import CurrencyChain
from .models.currency_pair import CurrencyPair
from .models.delivery_contract import DeliveryContract
from .models.delivery_settlement import DeliverySettlement
from .models.deposit_address import DepositAddress
from .models.funding_account import FundingAccount
from .models.funding_book_item import FundingBookItem
from .models.funding_rate_record import FundingRateRecord
from .models.futures_account import FuturesAccount
from .models.futures_account_book import FuturesAccountBook
from .models.futures_candlestick import FuturesCandlestick
from .models.futures_initial_order import FuturesInitialOrder
from .models.futures_liquidate import FuturesLiquidate
from .models.futures_order import FuturesOrder
from .models.futures_order_book import FuturesOrderBook
from .models.futures_order_book_item import FuturesOrderBookItem
from .models.futures_price_trigger import FuturesPriceTrigger
from .models.futures_price_triggered_order import FuturesPriceTriggeredOrder
from .models.futures_ticker import FuturesTicker
from .models.futures_trade import FuturesTrade
from .models.insurance_record import InsuranceRecord
from .models.ledger_record import LedgerRecord
from .models.loan import Loan
from .models.loan_patch import LoanPatch
from .models.loan_record import LoanRecord
from .models.margin_account import MarginAccount
from .models.margin_account_book import MarginAccountBook
from .models.margin_account_currency import MarginAccountCurrency
from .models.margin_borrowable import MarginBorrowable
from .models.margin_currency_pair import MarginCurrencyPair
from .models.margin_transferable import MarginTransferable
from .models.multi_chain_address_item import MultiChainAddressItem
from .models.my_futures_trade import MyFuturesTrade
from .models.open_orders import OpenOrders
from .models.options_account import OptionsAccount
from .models.options_account_book import OptionsAccountBook
from .models.options_contract import OptionsContract
from .models.options_my_trade import OptionsMyTrade
from .models.options_order import OptionsOrder
from .models.options_position import OptionsPosition
from .models.options_position_close import OptionsPositionClose
from .models.options_settlement import OptionsSettlement
from .models.options_ticker import OptionsTicker
from .models.options_underlying import OptionsUnderlying
from .models.options_underlying_ticker import OptionsUnderlyingTicker
from .models.order import Order
from .models.order_book import OrderBook
from .models.position import Position
from .models.position_close import PositionClose
from .models.position_close_order import PositionCloseOrder
from .models.repay_request import RepayRequest
from .models.repayment import Repayment
from .models.spot_account import SpotAccount
from .models.spot_price_put_order import SpotPricePutOrder
from .models.spot_price_trigger import SpotPriceTrigger
from .models.spot_price_triggered_order import SpotPriceTriggeredOrder
from .models.sub_account_balance import SubAccountBalance
from .models.sub_account_transfer import SubAccountTransfer
from .models.ticker import Ticker
from .models.total_balance import TotalBalance
from .models.trade import Trade
from .models.trade_fee import TradeFee
from .models.transfer import Transfer
from .models.trigger_order_response import TriggerOrderResponse
from .models.withdraw_status import WithdrawStatus
