
[options]
# data_dir = /home/kyaw-zay/.local/share/Odoo
admin_passwd = 21825174
db_host = localhost
db_port = 5432
db_user = admin
db_password = admin
http_port = 6060

addons_path=/home/kyaw-zay/HTS/Odoo15/odoo15_default/addons,/home/kyaw-zay/HTS/Odoo15/custom_addons,/home/kyaw-zay/HTS/Odoo15/custom_addons/jwt_provider,/home/kyaw-zay/HTS/Odoo15/custom_addons/master_data_api
# log_level = debug
# dev_mode = True
application=True
list_db = True